trigger:
- master

pool:
  'My_local_host_agent'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:


- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'