trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.x'
  inputs:
    version: '3.x'
    includePreviewVersions: true

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'x64'
    configuration: 'Release'
