trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.x'
  inputs:
    version: '3.x'
    includePreviewVersions: true

- task: MSBuild@1
  displayName: Build for $(BuildConfiguration)
  inputs:
    solution: DotNetConf.sln
    msbuildArguments: /restore 
    configuration: $(BuildConfiguration)
    platform: x64
    maximumCpuCount: false
